# Generated by Django 5.0.2 on 2024-03-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='image',
            field=models.CharField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png', max_length=255, null=True),
        ),
    ]
